workdir : /home/u/sr467/scratch/projects/20120810_LewisS_AM_MMhmeDIP
threads : 16
data : /home/u/sr467/scratch/projects/20120810_LewisS_AM_MMhmeDIP/config/cluster-samples.csv
paired : False
genome :
    build : GRCm38
    sequence : /home/u/sr467/scratch/projects/20120810_LewisS_AM_MMhmeDIP/genome/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
    genes : /home/u/sr467/scratch/projects/20120810_LewisS_AM_MMhmeDIP/genome/mm10-gencode_vm23.bed
    blacklist : /home/u/sr467/scratch/projects/20120810_LewisS_AM_MMhmeDIP/genome/mm10.blacklist.bed

fastq_screen_config : /home/u/sr467/scratch/projects/20120810_LewisS_AM_MMhmeDIP/config/fastq_screen.config
