workdir : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/hmeDip-Seq/analysis
threads : 6
data : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/hmeDip-Seq/config/samples.csv
paired : False
genome :
    build : GRCm38
    sequence : /media/stephen/Data/genomes/GRCm38/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
    genes : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/hmeDip-Seq/mm10-gencode_vm23.bed
    blacklist : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/hmeDip-Seq/genome/mm10.blacklist.bed

fastq_screen_config : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/hmeDip-Seq/config/fastq_screen.config
