module_order:
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*.raw_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*.trim_fastqc.zip'
    - fastq_screen:
        name: 'FastQ Screen (trimmed sequences)'
    - bowtie2
    - samtools
    - featureCounts
    - deeptools
    - macs2

custom_plot_config:
    deeptools_correlation:
        cmap: viridis

log_filesize_limit: 100000000

remove_sections:
    - samtools-stats-alignment

extra_fn_clean_exts:
    - '.'
